Eliza Cloud Application
Reintroducing just the packaging changes

merge

parent 5cd3e3641452887add29cdd8fa5985995e872fc8
author mike dupont <mike.dupont@introspector.local> 1739535451 -0500
committer mike dupont <mike.dupont@introspector.local> 1741907096 -0400

update

parent 5cd3e3641452887add29cdd8fa5985995e872fc8
author mike dupont <mike.dupont@introspector.local> 1739535451 -0500
committer mike dupont <mike.dupont@introspector.local> 1741907039 -0400

rebase

parent 5cd3e3641452887add29cdd8fa5985995e872fc8
author mike dupont <mike.dupont@introspector.local> 1739535451 -0500
committer mike dupont <mike.dupont@introspector.local> 1741906133 -0400

parent 5cd3e3641452887add29cdd8fa5985995e872fc8
author mike dupont <mike.dupont@introspector.local> 1739535451 -0500
committer mike dupont <mike.dupont@introspector.local> 1741906107 -0400

rebase

parent 5cd3e3641452887add29cdd8fa5985995e872fc8
author mike dupont <mike.dupont@introspector.local> 1739535451 -0500
committer mike dupont <mike.dupont@introspector.local> 1741906047 -0400

now updated by removing all changes

adding my files back in

readme

replaced vec with arch specific, ugh

addin the sqlite vec back in

transfer

update

update

update

update

adding buildspec parameters

update

fixup it run

workaround  TS2741: Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.

removing the timeout

workaround for build error

client:build: > client@ build /mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/client
client:build: > pnpm run extract-version && tsc -b && vite build
client:build:
client:build:
client:build: > client@ extract-version /mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/client
client:build: > bash ./version.sh
client:build:
client:build: info.json created with version: 0.25.6-alpha.1
client:build: src/components/audio-recorder.tsx:203:13 - error TS2741: Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.
client:build:
client:build: 203             timerTimeout = setTimeout(() => {
client:build:                 ~~~~~~~~~~~~
client:build:
client:build:   ../node_modules/@types/node/timers.d.ts:130:17
client:build:     130                 [Symbol.dispose](): void;
client:build:                         ~~~~~~~~~~~~~~~~
client:build:     '[Symbol.dispose]' is declared here.
client:build:
client:build:
client:build: Found 1 error.

adding multiply script

removing packages to match develop

remove key

fixed

removing client for now, sorry

build success

now running with remote debugging

adding experimental chars

adding launch for example

vendored twitter

updated client-twitter wip

updated client-twitter wip

updated client-twitter wip

updated client-twitter wip

updated client-twitter wip

integrate twitter client into agent

lets test

update submodules

update submodules

update submodules

adhoc changes

reintroduce changes

update packages

betting on this one

this worrks locally

fix

move the login to the head

bugfix

update service

change docker version in tokenizer

major update

just load all the chars in the char directory,

If you dont want them, delete them.

wip

wip

wip

update vendor/elizaos/client-twitter

start of adding discord

runs and errors

update submodules

add perms

adding ffmpeg

update submodules

adding new module tts

wip

wip

wip

wip

wip

update submodules

debug DISCORD

now we are testing just discord via default char in debug mode

update

update

adding debugging

working much better

update submodules

submodules

use new get secrets

use number 7

adding ffmpeg to final image

docker

adding telegram

update buildspec

removing wrong code